application: rockt-ga
version: 1
runtime: python
api_version: 1

builtins: 
- remote_api: on
- datastore_admin: on
- appstats: on 

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /streetcars
  script: main.py

- url: /update
  script: update.py
  login: admin

- url: /query[/]?.*
  script: main.py

- url: /import
  script: importer.py

- url: /assets
  static_dir: assets

- url: /car
  script: main.py

- url: /user
  script: main.py

- url: /remote_api
  script: /home/sib/Devel/ga/google/appengine/ext/remote_api/handler.py
  login: admin
