application: rockt-ga
version: 1
runtime: python
api_version: 1

builtins: 
- remote_api: on

handlers:
- url: /
  script: main.py
- url: /update
  script: update.py
  login: admin
- url: /import
  script: importer.py


